[providers]
python = {}

[build]
cmd = ["pip", "install", "-r", "requirements.txt"]

[start] 
cmd = ["uvicorn", "workforce_api.main:app", "--host", "0.0.0.0", "--port", "$PORT"]

[variables]
PYTHONPATH = "/app"
NIXPACKS_PYTHON_VERSION = "3.11" 